on: [push]
jobs:
  build:
    name: Run MATLAB Build
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: r2020b
      - name: Run build
        uses: matlab-actions/run-command@v2
        with:
          command: ver
